# Generated by Django 4.1.3 on 2023-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_infor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laction', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('Bus_no', models.EmailField(max_length=35)),
            ],
        ),
    ]
