# Generated by Django 4.1.3 on 2023-01-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter_infor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus_infor',
            old_name='Laction',
            new_name='Location',
        ),
    ]
